### PR TITLE
Continue reading after ping

### PR DESCRIPTION
**Pull request by nshmyrev**
Now it just returns garbage payload, I think it is more reasonable to continue reading.

### CODE REVIEW

**Comment by sirn-se** [comment]
Not sure why Travis doesn't report back, but tests are failing for this PR.

https://travis-ci.org/github/Textalk/websocket-php/builds/697930550

**Comment by nshmyrev** [comment]
@sirn-se  Sorry, I didn't notice it.

Its more a design decision - are you ok with automated pong? Then I can modify the tests to skip pingpong test. Or do I need to check getLastOpcode every time I call receive to respond properly in my client?

I'm trying to interoperate with python websockets library, it sends periodic pings on timer and client must respond or the server closes the connection.

**Comment by sirn-se** [comment]
@nshmyrev

Sorry about late answer, although I do understand the practicality of these changes we needed to confirm it with specifications and ensure it's not a breaking change.

Looking at the WebSocket specification, it states that Ping frames MAY include application data. Unlike Close frames, it does not state that application data must not be shown to user.

https://tools.ietf.org/html/rfc6455#section-5.5.2

My interpretation is that the payload of Ping frames **should** be returned to calling code.
Possibly we could ignore frames with empty payload, but the downside is that we introduce inconsistencies without removing the need to check opcode.

If you have another interpretation of the specifications, please tell me.
I do have an idea how to resolve this, but that include a major rewrite and I don't know when I'll have time for it (this project is no longer endorsed by my employer, so I'm doing this in my spare time).

**Comment by nshmyrev** [comment]
> My interpretation is that the payload of Ping frames should be returned to calling code.

There is no direct mention about this, but there are things like 

> An endpoint MUST be capable of handling control frames in the middle of a fragmented message.

This doesn't work currently if you receive ping inside fragment

> Each frame belonging to the same  message contains the same type of data.  Broadly speaking, there are types for textual data (which is interpreted as UTF-8 [RFC3629] text), binary data (whose interpretation is left up to the  application), and control frames (which are **not intended** to carry data for the application but instead for protocol-level signaling, such as to signal that the connection should be closed)

So ping frame (which is a control frame) is not intended for the application.

Overall, the problem with the current API is that I can't really identify the type of the opcode properly, should I just check lastOpcode if I want to distinguish text/binary?

**Comment by sirn-se** [comment]
Yes, I suppose the benefit of handling control frames received between fragmented message frames correctly is greater than the ability to receive content on ping frames (I still think the specification is a bit unclear on this). So let's do this.

Could you add tests (or expand existing tests) to verify a flow where a ping frame received between two frames of a fragmented text message, it would be great.

**Comment by Bradez** [comment]
This PR appears to fix an issue that me and my team have been experiencing wherein, if a `ping` request comes through, our subsequent response will be empty. This has been reproducible internally and consistently for us, and after applying this fix, all subsequent responses (indefinitely) were valid and correct.

I hope to see this merged sooner rather later. In the meantime, we'll be using the patch. 👍

**Comment by nshmyrev** [comment]
@Bradez Thank you Brad, I suppose the issue is to write a test for the case which I kind of forgot. If you can help with the test it would be great!

**Comment by sirn-se** [comment]
Besides fixing the tests there were some other things needed to be fix, lika introduces similar handling of `pong` messages.

Did a new PR to replace this one, perhaps @Bradez can verify that it solves the issues you're having?
https://github.com/Textalk/websocket-php/pull/101

Closing this.

**Comment by Bradez** [comment]
@sirn-se, I can confirm the new PR works. 👍

**Pull request closed without merging**
