### PR TITLE
Update Client.php

### PR DESCRIPTION
**Pull request by xxnoobmanxx**
Faster response reading from websocket server for the handshake.

### CODE REVIEW

**Comment by fiddur** [comment]
Testing on 5.3, 5.4, 5.5 all fails with on this pr:

Fatal error:  Uncaught exception 'WebSocket\ConnectionException' with message 'Could not open socket to "localhost:8000": Connection refused (111).'

**Comment by xxnoobmanxx** [comment]
sounds like a "server is not accessible" to me.
Have you tried a telnet test? 

telnet 127.0.0.1 8000

this should return: 
Trying 127.0.0.1...
Connected to localhost.

**Comment by fiddur** [comment]
The server is brought up by the test itself, and it work on master without this branch.  I'll try rerunning it, but since it failed on all 3 it didn't seem like a random error.  Looking at the suggested code changes I don't see the problem though…

**Comment by fiddur** [comment]
When I run it locally, the test passes, but much slower.

Time, as reported from phpunit:
3 runs with your patch: avg 1.94 minutes. (quite close all three)
3 runs without the patch: avg 42 seconds (also close in time).

I guess travis catches some timeout, but this seems to suggest that it's slower with your patch.

Have you tried running the tests or some other way to indicate that your code is faster?

**Comment by xxnoobmanxx** [comment]
I ran your client from a remote server, with fast-cgi.
The websocket server is based on Ratchet Project (http://socketo.me).

With the previous code, at the line: $metadata = stream_get_meta_data($this->socket); (line 121) XDebug tells me this is invoked up to 5 times, about 5 to 6 secods each time (up to 30s). I think its because of the loop its inside.

Witth 'stream_get_contents ' the same script runs in a total of 5 seconds.

One thing i noticed, is that the minimum time is 5 seconds. People on stackoverflow told me its because of the ratchet server. http://stackoverflow.com/questions/32226075/websocket-push-with-php-taking-too-long

**Comment by xxnoobmanxx** [comment]
Its not explicit on websocket rfc but, accordingly to some doc i read before, the maximum length of the server response is 200 bytes. maybe if you run a test with this limit, the script should run faster:

$response = stream_get_contents ($this->socket, 200);

But , some server sends additional data before the key. This means the handshake response key could be incomplete and the requisition will fail.

**Comment by fiddur** [comment]
Reading the full stream is not correct, since there MIGHT be a websocket frame directly after the header.

I have changed the header-reading to end at the empty line that really ends the header.  The tests now run on 25 seconds instead of 42 (or on your branch almost 2 minutes).

Try it out and see how it works with ratchet.

**Comment by xxnoobmanxx** [comment]
I think stream_get_contents does this automatically already, but in other case, if you want to check it manually, maybe you could check for the 2 line endings ("\r\n\r\n") instead of a empty line.

Eg: strpos( $response, "\r\n\r\n" ) !== false

**Comment by fiddur** [comment]
It could be possible to use `stream_get_contents`; it reads the entire stream, and that would have to be split on `\r\n\r\n` and the rest, if any, must be stored for reading an incoming websocket frame.

I guess we would need to add a test for a server sending a frame in the same TCP package as the header…

Have you tried the new version against ratchet?  If you could add a test imitating the ratchett server and showing that it is much faster with `stream_get_contents`, I could go forward with the code for storing excess frame data.  Otherwise, it seems the version in branch `devHeaderEnding` is good.

**Comment by xxnoobmanxx** [comment]
test_stream_get_line
test_stream_get_contents

Here are my tests... one of them with the stream_get_line loop and another with get_contents.
This loop looks better than the other but, as you can see in the images, it took 4 X cumulative time.  

For these tests I used the lastest ratchet version, both sending the message "test" on the same host

**Comment by fiddur** [comment]
Based on your stackoverflow-link, you're hunting a 10 second delay, and you do it by cutting 20 milliseconds?

I can see sense in cutting 20 milliseconds in the hand-shake, though, but it has to be weighed both against the time to split and store an eventual coming frame, and the added complexity.

I don't have time to install and trace the specific problems with ratchet right now, but the tests with the local websocket server runs almost 5 times faster with the code in devHeaderEncoding than in your pull request…

**Comment by fiddur** [comment]
Ok I lied, I found time :)

I'll make some tests with a ratchet server as well to see if I can replicate your problem.

**Comment by fiddur** [comment]
So, I made a basic ratchet server mimicing the `examples/echoserver.php` that is used in the tests and ran the tests against that.  The speed is quite identical; on this machine  6.8 - 6.9 seconds regardless of echoserver in local code or ratchet code.  This is on `devHeaderEncoding` branch.

On your branch, it takes…  well, it dies from timeout.

So I ask you again: Have you tried `devHeaderEncoding` on the real code?  Not micro-optimizing 20 ms, but adressing the 10 seconds you had a problem with?

I'm thinking of adding the ratchet-echoserver as an autotest as well, since others have had problems earlier with using this lib against a ratchet server…

**Comment by xxnoobmanxx** [comment]
The 10 sec delay was because a dns misconfiguration on the local network (Im not a infrastructure guy, so I really dont know what configuration was it).

And yes, those tests were made using devHeaderEncoding, using the real scenario code in a local network server.

The production server wasn't updated yet, but its hosted by amazon, with a better connection and high specs.

**Comment by fiddur** [comment]
Ok, trying another one then.  I've added a ratchet echoserver in the test suite, and I've changed the header receiving loop to:
`$response = stream_get_line($this->socket, 1024, "\r\n\r\n");`

**Comment by fiddur** [comment]
devHeaderEncoding is now merged.  It does a single read and is quite microoptimized.

**Pull request closed without merging**
